name: 353-study-guide

services:

  frontend:
    build: ./frontend
    ports:
      - 80:5173
    volumes:
      - ./frontend:/app/
      - /app/node_modules
    stdin_open: true
    tty: true

  backend:
    build: ./backend
    ports:
      - 81:3000
    volumes:
      - ./backend:/app/
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/quiz

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quiz
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d quiz"]
      interval: 5s
      timeout: 5s
      retries: 5