name: 353-study-guide

services:

  frontend:
    build: ./frontend
    ports:
      - 80:5173
    volumes:
      - ./frontend:/app/
      - /app/node_modules
    stdin_open: true
    tty: true

  backend:
    build: ./backend
    ports:
      - 81:3000
    volumes:
      - ./backend:/app/
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      # named volume of postgres data
      - pgdata:/var/lib/postgresql/data

      # host mount sql files to create tables and seed data on first container creation
      - ./backend/scripts/01-init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./backend/scripts/02-seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
      - ./backend/scripts/03-add-topics.sql:/docker-entrypoint-initdb.d/03-add-topics.sql
      - ./backend/scripts/04-seed-containerization.sql:/docker-entrypoint-initdb.d/04-seed-containerization.sql
      - ./backend/scripts/05-seed-js-html-http.sql:/docker-entrypoint-initdb.d/05-seed-js-html-http.sql
      - ./backend/scripts/06-seed-js-ts-react.sql:/docker-entrypoint-initdb.d/06-seed-js-ts-react.sql
      - ./backend/scripts/07-seed-sql-react-rest.sql:/docker-entrypoint-initdb.d/07-seed-sql-react-rest.sql
      - ./backend/scripts/08-seed-rest-mcp-nosql-llm.sql:/docker-entrypoint-initdb.d/08-seed-rest-mcp-nosql-llm.sql
    env_file:
      - ./backend/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pguser -d quiz"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: