INSERT INTO questions (question_text) VALUES
  ('Which component of full stack development includes UI, layout, and user interaction?'),
  ('Which of the following is a front-end framework?'),
  ('Which component handles data storage, processing, and retrieval?'),
  ('Which of the following is a back-end programming language?'),
  ('Which of the following is a back-end framework?'),
  ('Which technology is used to store and retrieve application data?'),
  ('Which of the following is a database management system (DBMS)?'),
  ('What does CRUD stand for?'),
  ('Which HTTP method is typically used for retrieving data?'),
  ('Which HTTP method is typically associated with creating new resources?'),
  ('What is stateless communication?'),
  ('What is the role of a hypervisor?'),
  ('Which statement best describes a virtual machine?'),
  ('Which statement best describes a container?'),
  ('Which tools are commonly used for deployment and orchestration?');

INSERT INTO options (question_id, option_text, is_correct) VALUES
  (1, 'Back-end technologies', false),
  (1, 'Database technologies', false),
  (1, 'Front-end technologies', true),
  (1, 'Deployment and hosting', false),
  (2, 'Django', false),
  (2, 'Express.js', false),
  (2, 'React', true),
  (2, 'Flask', false),
  (3, 'Front-end technologies', false),
  (3, 'Back-end technologies', true),
  (3, 'Deployment tools', false),
  (3, 'WebAssembly', false),
  (4, 'HTML', false),
  (4, 'CSS', false),
  (4, 'Python', true),
  (4, 'Vue.js', false),
  (5, 'Angular', false),
  (5, 'Django', true),
  (5, 'MongoDB', false),
  (5, 'Kubernetes', false),
  (6, 'Database technologies', true),
  (6, 'Front-end frameworks', false),
  (6, 'Hypervisors', false),
  (6, 'WebAssembly', false),
  (7, 'React', false),
  (7, 'MySQL', true),
  (7, 'Express.js', false),
  (7, 'Docker', false),
  (8, 'Create, Run, Update, Deploy', false),
  (8, 'Create, Read, Update, Delete', true),
  (8, 'Connect, Retrieve, Upload, Download', false),
  (8, 'Compile, Render, Upload, Delete', false),
  (9, 'POST', false),
  (9, 'GET', true),
  (9, 'PUT', false),
  (9, 'DELETE', false),
  (10, 'GET', false),
  (10, 'DELETE', false),
  (10, 'POST', true),
  (10, 'PATCH', false),
  (11, 'The server stores client session state permanently', false),
  (11, 'Each request is independent and based on current state', true),
  (11, 'Clients never send requests to servers', false),
  (11, 'The server cannot respond to requests', false),
  (12, 'Manages front-end frameworks', false),
  (12, 'Allows multiple virtual machines to run on one physical machine', true),
  (12, 'Stores application data', false),
  (12, 'Deploys containers to the cloud', false),
  (13, 'A lightweight package sharing the host OS kernel', false),
  (13, 'A software emulation of a physical machine with its own OS', true),
  (13, 'A database management system', false),
  (13, 'A client-side scripting environment', false),
  (14, 'Runs a full separate OS on a hypervisor', false),
  (14, 'Provides total isolation with high resource cost', false),
  (14, 'Lightweight package including everything needed to run an application', true),
  (14, 'Only used for database management', false),
  (15, 'HTML and CSS', false),
  (15, 'Docker and Kubernetes', true),
  (15, 'React and Vue.js', false),
  (15, 'MySQL and PostgreSQL', false);